# TruffleHog Configuration for lumpsum.in
# Custom rules for detecting secrets

detectors:
  # API Keys
  - name: "API Key - Generic"
    regex: (?i)(api[_-]?key|apikey|api_key|api-key)\s*[:=]\s*['"]?[a-zA-Z0-9]{32,}['"]?
    
  - name: "Google API Key"
    regex: AIza[0-9A-Za-z\\-_]{35}
    
  - name: "GitHub Token"
    regex: (ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{36}
    
  - name: "GitHub App Token"
    regex: ghs_[A-Za-z0-9_]{36}
    
  - name: "GitHub Personal Access Token"
    regex: ghp_[A-Za-z0-9_]{36}
    
  - name: "GitHub OAuth Token"
    regex: gho_[A-Za-z0-9_]{36}
    
  - name: "GitHub User to Server Token"
    regex: ghu_[A-Za-z0-9_]{36}
    
  - name: "GitHub Server to Server Token"
    regex: ghs_[A-Za-z0-9_]{36}
    
  - name: "GitHub Refresh Token"
    regex: ghr_[A-Za-z0-9_]{36}
    
  # AWS
  - name: "AWS Access Key ID"
    regex: AKIA[0-9A-Z]{16}
    
  - name: "AWS Secret Access Key"
    regex: (?i)aws[_-]?secret[_-]?access[_-]?key\s*[:=]\s*['"]?[A-Za-z0-9/+=]{40}['"]?
    
  # Database URLs
  - name: "Database URL with Password"
    regex: (?i)(postgresql?|mysql|mongodb)://[^:]+:[^@]+@[^/]+/[^?\s]+
    
  # JWT Tokens
  - name: "JWT Token"
    regex: eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*
    
  # Private Keys
  - name: "RSA Private Key"
    regex: -----BEGIN RSA PRIVATE KEY-----
    
  - name: "DSA Private Key"
    regex: -----BEGIN DSA PRIVATE KEY-----
    
  - name: "EC Private Key"
    regex: -----BEGIN EC PRIVATE KEY-----
    
  - name: "OpenSSH Private Key"
    regex: -----BEGIN OPENSSH PRIVATE KEY-----
    
  - name: "PGP Private Key"
    regex: -----BEGIN PGP PRIVATE KEY BLOCK-----
    
  # OAuth
  - name: "OAuth Client Secret"
    regex: (?i)(client[_-]?secret|client_secret|client-secret)\s*[:=]\s*['"]?[a-zA-Z0-9]{16,}['"]?
    
  # reCAPTCHA
  - name: "reCAPTCHA Secret Key"
    regex: 6L[0-9A-Za-z-_]{35}
    
  # Stripe
  - name: "Stripe Secret Key"
    regex: sk_live_[0-9a-zA-Z]{24}
    
  - name: "Stripe Publishable Key"
    regex: pk_live_[0-9a-zA-Z]{24}
    
  # Slack
  - name: "Slack Bot Token"
    regex: xoxb-[0-9]{12}-[0-9]{12}-[a-zA-Z0-9]{24}
    
  - name: "Slack User Token"
    regex: xoxp-[0-9]{12}-[0-9]{12}-[a-zA-Z0-9]{24}
    
  # Discord
  - name: "Discord Bot Token"
    regex: [MN][a-zA-Z0-9]{23}\.[\w-]{6}\.[\w-]{27}
    
  # Firebase
  - name: "Firebase API Key"
    regex: AIza[0-9A-Za-z\\-_]{35}
    
  # Google Cloud
  - name: "Google Cloud API Key"
    regex: AIza[0-9A-Za-z\\-_]{35}
    
  # Passwords in code
  - name: "Hardcoded Password"
    regex: (?i)(password|passwd|pwd)\s*[:=]\s*['"]?[^'"]{8,}['"]?
    
  # Environment variables with secrets
  - name: "Secret in Environment Variable"
    regex: (?i)(secret|key|token|password)\s*[:=]\s*['"]?[a-zA-Z0-9]{16,}['"]?

# Exclude patterns
exclude:
  - "node_modules/"
  - ".git/"
  - "dist/"
  - "build/"
  - ".next/"
  - "coverage/"
  - "*.min.js"
  - "*.bundle.js"
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "*.log"
  - "*.tmp"
  - ".env.example"
  - "env.local.example"
  - "test-recaptcha.html"
  - "security/secret-scan-REPORT.txt"
  - ".trufflehog.yaml"

# Scan configuration
only-verified: false
fail: true
json: false
