name: CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ chore/v2-green-and-future-proof ]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install
        run: npm ci
        working-directory: frontend
      - name: Setup .env for CI
        run: |
          echo 'DATABASE_URL="file:./dev.db"' > frontend/.env
          echo 'NEXTAUTH_URL="http://localhost:3000"' >> frontend/.env
          echo 'NEXTAUTH_SECRET="testsecret"' >> frontend/.env
          echo 'GOOGLE_CLIENT_ID="test"' >> frontend/.env
          echo 'GOOGLE_CLIENT_SECRET="test"' >> frontend/.env
          echo 'RECAPTCHA_SECRET_KEY="test"' >> frontend/.env
        working-directory: frontend
      - name: Prisma generate
        run: node scripts/prisma-generate.js
        working-directory: frontend
      - name: Lint
        run: npm run lint
        working-directory: frontend
      - name: Typecheck
        run: npm run typecheck
        working-directory: frontend
      - name: Audit
        run: npm audit --audit-level=high || true
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend


