name: CI

on:
  pull_request:
    branches: [ main, release/V_2.0 ]
  push:
    branches: [ chore/frontend-ci-fixes-and-preview-env ]

jobs:
  prisma-generate:
    name: Prisma Generate
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npx prisma generate --schema ./prisma/schema.prisma

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [prisma-generate]
    defaults: 
      run: 
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run lint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [prisma-generate]
    defaults: 
      run: 
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run typecheck

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: [prisma-generate]
    defaults: 
      run: 
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm audit --audit-level=high || true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, typecheck, prisma-generate]
    defaults: 
      run: 
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npx prisma generate --schema ./prisma/schema.prisma
      - run: npm run build

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [prisma-generate]
    defaults: 
      run: 
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm test -- --ci --reporters=default

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [build]
    defaults: 
      run: 
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npx prisma generate --schema ./prisma/schema.prisma
      - run: npm run e2e --if-present


