name: CI

on:
  push:
    branches: [ main, master, feature/** ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Setup .env for CI
        run: |
          echo 'DATABASE_URL="file:./dev.db"' > .env
          echo 'NEXTAUTH_URL="http://localhost:3000"' >> .env
          echo 'NEXTAUTH_SECRET="testsecret"' >> .env

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Sync DB
        run: npx prisma db push

      - name: Seed DB
        run: npm run db:seed

      - name: Typecheck
        run: npm run typecheck

      - name: Tests
        run: npm test --silent

      - name: Build
        run: npm run build

      - name: Backend install
        run: npm install --prefix backend

      - name: Backend typecheck
        run: npm run typecheck --prefix backend

      - name: Backend build
        run: npm run build --prefix backend

      - name: Backend tests
        env:
          DATABASE_URL: "file:../prisma/dev.db"
          JWT_SECRET: "testsecret_testsecret"
        run: npm test --prefix backend --silent


